export const DEMO_CATEGORIES = [
  { id: 'cat-1', name: '3D tisk', slug: '3d-tisk', icon: '🖨️', description: 'FDM, SLA, resin tisk na zakázku', sort_order: 1 },
  { id: 'cat-2', name: 'Klasický tisk', slug: 'klasicky-tisk', icon: '🖼️', description: 'Vizitky, letáky, brožury, plakáty', sort_order: 2 },
  { id: 'cat-3', name: 'Potisk textilu', slug: 'potisk-textilu', icon: '👕', description: 'DTF, DTG, sítotisk, sublimace', sort_order: 3 },
  { id: 'cat-4', name: 'Laser & CNC', slug: 'laser-cnc', icon: '⚡', description: 'Gravírování, řezání, frézování', sort_order: 4 },
  { id: 'cat-5', name: 'Velkoformát', slug: 'velkoformat', icon: '🖼️', description: 'Bannery, rollupy, samolepky', sort_order: 5 },
  { id: 'cat-6', name: 'Handmade', slug: 'handmade', icon: '🎨', description: 'Originální výrobky, dekorace', sort_order: 6 },
];

export const DEMO_MAKERS = [
  {
    id: 'maker-1',
    company_name: 'PrintHub Praha',
    city: 'Praha',
    bio: 'Profesionální 3D tisk na zakázku. Specialisty na prototypy, funkční díly a architektonické modely. Nabízíme FDM i SLA tisk.',
    rating_avg: 4.8,
    rating_count: 42,
    total_orders: 156,
    is_verified: true,
    ico: '12345678',
    created_at: '2025-01-15',
  },
  {
    id: 'maker-2',
    company_name: 'MakerSpace Brno',
    city: 'Brno',
    bio: 'Komunitní dílna s 3D tiskárnami, laserem a CNC frézkou. Vyrábíme prototypy, reklamní předměty a originální dárky.',
    rating_avg: 4.6,
    rating_count: 28,
    total_orders: 89,
    is_verified: true,
    ico: '23456789',
    created_at: '2025-02-20',
  },
  {
    id: 'maker-3',
    company_name: 'Textil Factory',
    city: 'Ostrava',
    bio: 'Potisk triček, mikin a pracovního oblečení. DTF a sítotisk. Zakázky od 1 kusu. Expresní dodání do 48 hodin.',
    rating_avg: 4.9,
    rating_count: 67,
    total_orders: 312,
    is_verified: true,
    ico: '34567890',
    created_at: '2024-11-10',
  },
  {
    id: 'maker-4',
    company_name: 'LaserCut Studio',
    city: 'Plzeň',
    bio: 'Laserové gravírování a řezání. Dřevo, plexisklo, kůže, papír. Personalizované dárky a firemní předměty.',
    rating_avg: 4.7,
    rating_count: 35,
    total_orders: 178,
    is_verified: true,
    ico: '45678901',
    created_at: '2025-03-05',
  },
  {
    id: 'maker-5',
    company_name: 'NovaPrint',
    city: 'Liberec',
    bio: 'Tiskárna s tradicí od roku 2010. Vizitky, letáky, brožury, plakáty. Ofsetový i digitální tisk nejvyšší kvality.',
    rating_avg: 4.5,
    rating_count: 19,
    total_orders: 67,
    is_verified: false,
    ico: '56789012',
    created_at: '2025-04-12',
  },
  {
    id: 'maker-6',
    company_name: 'VelkoTisk CZ',
    city: 'Olomouc',
    bio: 'Velkoformátový tisk — bannery, rollupy, samolepky, polepy aut. Tisk na plátno a fotopapír. Montáž po celé ČR.',
    rating_avg: 4.3,
    rating_count: 14,
    total_orders: 45,
    is_verified: true,
    ico: '67890123',
    created_at: '2025-04-28',
  },
  {
    id: 'maker-7',
    company_name: 'Handmade by Terka',
    city: 'České Budějovice',
    bio: 'Originální ručně vyráběné dekorace, šperky a doplňky z pryskyřice, dřeva a kovu. Každý kus je unikát.',
    rating_avg: 5.0,
    rating_count: 23,
    total_orders: 89,
    is_verified: true,
    ico: '78901234',
    created_at: '2025-01-30',
  },
  {
    id: 'maker-8',
    company_name: '3D Modelárna',
    city: 'Hradec Králové',
    bio: 'Resinový 3D tisk pro šperky, miniatury a detailní modely. Specializace na tabletop gaming a cosplay.',
    rating_avg: 4.4,
    rating_count: 31,
    total_orders: 124,
    is_verified: false,
    ico: '89012345',
    created_at: '2025-02-14',
  },
  {
    id: 'maker-9',
    company_name: 'PrintXpress',
    city: 'Praha',
    bio: 'Rychlý digitální tisk do 24h. Vizitky za hodinu, letáky do druhého dne. Rozvoz po Praze zdarma.',
    rating_avg: 4.2,
    rating_count: 8,
    total_orders: 34,
    is_verified: true,
    ico: '90123456',
    created_at: '2025-05-01',
  },
];

export const DEMO_PRODUCTS = [
  {
    id: 'prod-1',
    maker_id: 'maker-1',
    title: 'FDM 3D tisk na zakázku',
    description: 'Tisk z PLA, PETG, ASA. Cena za hodinu tisku. Minimální objednávka 1 kus.',
    price: 350,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-01',
  },
  {
    id: 'prod-2',
    maker_id: 'maker-1',
    title: 'SLA Resin tisk — detailní modely',
    description: 'Přesnost 0.05mm. Ideální pro šperky, miniatury a prototypy.',
    price: 500,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-15',
  },
  {
    id: 'prod-3',
    maker_id: 'maker-3',
    title: 'Potisk triček — DTF',
    description: 'Plnobarevný potisk. Od 1 kusu. Trička značky Fruit of the Loom.',
    price: 299,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-3',
    created_at: '2025-02-10',
  },
  {
    id: 'prod-4',
    maker_id: 'maker-4',
    title: 'Gravírování do dřeva',
    description: 'Laserové gravírování fotografií, textů a log do bukového nebo dubového dřeva.',
    price: 450,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-4',
    created_at: '2025-03-20',
  },
  {
    id: 'prod-5',
    maker_id: 'maker-5',
    title: '1000 ks vizitek',
    description: '350g křídový papír, oboustranný plnobarevný tisk, laminace. Dodání do 3 dnů.',
    price: 890,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-2',
    created_at: '2025-04-01',
  },
  {
    id: 'prod-6',
    maker_id: 'maker-6',
    title: 'Roll-up banner 85×200 cm',
    description: 'Kvalitní roll-up s hliníkovou konstrukcí a plnobarevným tiskem.',
    price: 1490,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-5',
    created_at: '2025-04-15',
  },
  {
    id: 'prod-7',
    maker_id: 'maker-7',
    title: 'Pryskyřicový přívěsek na míru',
    description: 'Ručně vyráběný přívěsek z epoxidové pryskyřice. Barvy a design dle vašeho přání.',
    price: 350,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-6',
    created_at: '2025-02-28',
  },
  {
    id: 'prod-8',
    maker_id: 'maker-2',
    title: 'Prototyp z 3D tisku + CNC',
    description: 'Kompletní prototyp — 3D tištěné díly + CNC frézované kovové komponenty.',
    price: 0,
    price_type: 'on_request' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-10',
  },
];
