//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IPublicApi {

    /**
     * @param country (optional) 
     * @param category (optional) 
     * @param city (optional) 
     * @param minRating (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    makers(country: string | undefined, category: string | undefined, city: string | undefined, minRating: number | undefined, page: number | undefined, pageSize: number | undefined): Promise<PagedDataOfMakerListItem>;

    /**
     * @return OK
     */
    makers2(slug: string): Promise<MakerProfile>;

    /**
     * @return OK
     */
    products(productId: string): Promise<ProductDetail>;

    /**
     * @return OK
     */
    products2(country: string, productId: string, filename: string): Promise<void>;

    /**
     * @return OK
     */
    register(body: RegisterMakerRequest): Promise<void>;

    /**
     * @return OK
     */
    meGET(): Promise<void>;

    /**
     * @return OK
     */
    mePUT(body: UpdateProfileRequest): Promise<void>;

    /**
     * @return OK
     */
    changePassword(body: ChangePasswordRequest): Promise<void>;

    /**
     * @return OK
     */
    makerGET(): Promise<void>;

    /**
     * @return OK
     */
    makerPUT(body: UpdateMakerProfileRequest): Promise<void>;

    /**
     * @return OK
     */
    register2(body: RegisterRequest): Promise<void>;

    /**
     * @return OK
     */
    login(body: LoginRequest): Promise<void>;

    /**
     * @return OK
     */
    logout(): Promise<void>;

    /**
     * @return OK
     */
    refresh(): Promise<void>;

    /**
     * @return OK
     */
    confirmEmail(body: ConfirmEmailRequest): Promise<void>;

    /**
     * @return OK
     */
    requestPasswordReset(body: RequestPasswordResetRequest): Promise<void>;

    /**
     * @return OK
     */
    confirmPasswordReset(body: ConfirmPasswordResetRequest): Promise<void>;

    /**
     * @return OK
     */
    requestMagicLink(body: RequestMagicLinkRequest): Promise<void>;

    /**
     * @return OK
     */
    consumeMagicLink(body: ConsumeMagicLinkRequest): Promise<void>;

    /**
     * @param q (optional) 
     * @param country (optional) 
     * @return OK
     */
    autocomplete(q: string | undefined, country: string | undefined): Promise<void>;

    /**
     * @return OK
     */
    anonymous(): Promise<string>;
}

export class PublicApi implements IPublicApi {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:5104/";
    }

    /**
     * @param country (optional) 
     * @param category (optional) 
     * @param city (optional) 
     * @param minRating (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    makers(country: string | undefined, category: string | undefined, city: string | undefined, minRating: number | undefined, page: number | undefined, pageSize: number | undefined): Promise<PagedDataOfMakerListItem> {
        let url_ = this.baseUrl + "/api/v1/catalog/makers?";
        if (country === null)
            throw new globalThis.Error("The parameter 'country' cannot be null.");
        else if (country !== undefined)
            url_ += "country=" + encodeURIComponent("" + country) + "&";
        if (category === null)
            throw new globalThis.Error("The parameter 'category' cannot be null.");
        else if (category !== undefined)
            url_ += "category=" + encodeURIComponent("" + category) + "&";
        if (city === null)
            throw new globalThis.Error("The parameter 'city' cannot be null.");
        else if (city !== undefined)
            url_ += "city=" + encodeURIComponent("" + city) + "&";
        if (minRating === null)
            throw new globalThis.Error("The parameter 'minRating' cannot be null.");
        else if (minRating !== undefined)
            url_ += "minRating=" + encodeURIComponent("" + minRating) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMakers(_response);
        });
    }

    protected processMakers(response: Response): Promise<PagedDataOfMakerListItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PagedDataOfMakerListItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PagedDataOfMakerListItem>(null as any);
    }

    /**
     * @return OK
     */
    makers2(slug: string): Promise<MakerProfile> {
        let url_ = this.baseUrl + "/api/v1/catalog/makers/{slug}";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMakers2(_response);
        });
    }

    protected processMakers2(response: Response): Promise<MakerProfile> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MakerProfile.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ErrorDto.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MakerProfile>(null as any);
    }

    /**
     * @return OK
     */
    products(productId: string): Promise<ProductDetail> {
        let url_ = this.baseUrl + "/api/v1/catalog/products/{productId}";
        if (productId === undefined || productId === null)
            throw new globalThis.Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProducts(_response);
        });
    }

    protected processProducts(response: Response): Promise<ProductDetail> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProductDetail.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ErrorDto.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProductDetail>(null as any);
    }

    /**
     * @return OK
     */
    products2(country: string, productId: string, filename: string): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/files/products/{country}/{productId}/{filename}";
        if (country === undefined || country === null)
            throw new globalThis.Error("The parameter 'country' must be defined.");
        url_ = url_.replace("{country}", encodeURIComponent("" + country));
        if (productId === undefined || productId === null)
            throw new globalThis.Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        if (filename === undefined || filename === null)
            throw new globalThis.Error("The parameter 'filename' must be defined.");
        url_ = url_.replace("{filename}", encodeURIComponent("" + filename));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProducts2(_response);
        });
    }

    protected processProducts2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    register(body: RegisterMakerRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/makers/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    meGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMeGET(_response);
        });
    }

    protected processMeGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    mePUT(body: UpdateProfileRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/me";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMePUT(_response);
        });
    }

    protected processMePUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    changePassword(body: ChangePasswordRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/me/change-password";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangePassword(_response);
        });
    }

    protected processChangePassword(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    makerGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/me/maker";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMakerGET(_response);
        });
    }

    protected processMakerGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    makerPUT(body: UpdateMakerProfileRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/me/maker";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMakerPUT(_response);
        });
    }

    protected processMakerPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    register2(body: RegisterRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister2(_response);
        });
    }

    protected processRegister2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    login(body: LoginRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    logout(): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    refresh(): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/refresh";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRefresh(_response);
        });
    }

    protected processRefresh(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    confirmEmail(body: ConfirmEmailRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/confirm-email";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConfirmEmail(_response);
        });
    }

    protected processConfirmEmail(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    requestPasswordReset(body: RequestPasswordResetRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/request-password-reset";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRequestPasswordReset(_response);
        });
    }

    protected processRequestPasswordReset(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    confirmPasswordReset(body: ConfirmPasswordResetRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/confirm-password-reset";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConfirmPasswordReset(_response);
        });
    }

    protected processConfirmPasswordReset(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    requestMagicLink(body: RequestMagicLinkRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/request-magic-link";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRequestMagicLink(_response);
        });
    }

    protected processRequestMagicLink(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    consumeMagicLink(body: ConsumeMagicLinkRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/consume-magic-link";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConsumeMagicLink(_response);
        });
    }

    protected processConsumeMagicLink(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param q (optional) 
     * @param country (optional) 
     * @return OK
     */
    autocomplete(q: string | undefined, country: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/addresses/autocomplete?";
        if (q === null)
            throw new globalThis.Error("The parameter 'q' cannot be null.");
        else if (q !== undefined)
            url_ += "q=" + encodeURIComponent("" + q) + "&";
        if (country === null)
            throw new globalThis.Error("The parameter 'country' cannot be null.");
        else if (country !== undefined)
            url_ += "country=" + encodeURIComponent("" + country) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAutocomplete(_response);
        });
    }

    protected processAutocomplete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    anonymous(): Promise<string> {
        let url_ = this.baseUrl + "/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAnonymous(_response);
        });
    }

    protected processAnonymous(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : _responseText;
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }
}

export class ChangePasswordRequest implements IChangePasswordRequest {
    currentPassword!: string;
    newPassword!: string;

    [key: string]: any;

    constructor(data?: IChangePasswordRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.currentPassword = _data["currentPassword"];
            this.newPassword = _data["newPassword"];
        }
    }

    static fromJS(data: any): ChangePasswordRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangePasswordRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["currentPassword"] = this.currentPassword;
        data["newPassword"] = this.newPassword;
        return data;
    }
}

export interface IChangePasswordRequest {
    currentPassword: string;
    newPassword: string;

    [key: string]: any;
}

export class ConfirmEmailRequest implements IConfirmEmailRequest {
    token!: string;

    [key: string]: any;

    constructor(data?: IConfirmEmailRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): ConfirmEmailRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ConfirmEmailRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token;
        return data;
    }
}

export interface IConfirmEmailRequest {
    token: string;

    [key: string]: any;
}

export class ConfirmPasswordResetRequest implements IConfirmPasswordResetRequest {
    token!: string;
    newPassword!: string;

    [key: string]: any;

    constructor(data?: IConfirmPasswordResetRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"];
            this.newPassword = _data["newPassword"];
        }
    }

    static fromJS(data: any): ConfirmPasswordResetRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ConfirmPasswordResetRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token;
        data["newPassword"] = this.newPassword;
        return data;
    }
}

export interface IConfirmPasswordResetRequest {
    token: string;
    newPassword: string;

    [key: string]: any;
}

export class ConsumeMagicLinkRequest implements IConsumeMagicLinkRequest {
    token!: string;

    [key: string]: any;

    constructor(data?: IConsumeMagicLinkRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): ConsumeMagicLinkRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ConsumeMagicLinkRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token;
        return data;
    }
}

export interface IConsumeMagicLinkRequest {
    token: string;

    [key: string]: any;
}

export class ErrorDto implements IErrorDto {
    field!: string;
    code!: string;
    type?: number;
    details?: any;

    [key: string]: any;

    constructor(data?: IErrorDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.field = _data["field"];
            this.code = _data["code"];
            this.type = _data["type"];
            this.details = _data["details"];
        }
    }

    static fromJS(data: any): ErrorDto {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["field"] = this.field;
        data["code"] = this.code;
        data["type"] = this.type;
        data["details"] = this.details;
        return data;
    }
}

export interface IErrorDto {
    field: string;
    code: string;
    type?: number;
    details?: any;

    [key: string]: any;
}

export class LoginRequest implements ILoginRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class MakerListItem implements IMakerListItem {
    makerId!: string;
    slug!: string;
    companyName!: string;
    bio!: string | undefined;
    city!: string;
    isVerified!: boolean;
    ratingAverageBp!: number;
    ratingCount!: number;
    totalOrders!: number;

    [key: string]: any;

    constructor(data?: IMakerListItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.makerId = _data["makerId"];
            this.slug = _data["slug"];
            this.companyName = _data["companyName"];
            this.bio = _data["bio"];
            this.city = _data["city"];
            this.isVerified = _data["isVerified"];
            this.ratingAverageBp = _data["ratingAverageBp"];
            this.ratingCount = _data["ratingCount"];
            this.totalOrders = _data["totalOrders"];
        }
    }

    static fromJS(data: any): MakerListItem {
        data = typeof data === 'object' ? data : {};
        let result = new MakerListItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["makerId"] = this.makerId;
        data["slug"] = this.slug;
        data["companyName"] = this.companyName;
        data["bio"] = this.bio;
        data["city"] = this.city;
        data["isVerified"] = this.isVerified;
        data["ratingAverageBp"] = this.ratingAverageBp;
        data["ratingCount"] = this.ratingCount;
        data["totalOrders"] = this.totalOrders;
        return data;
    }
}

export interface IMakerListItem {
    makerId: string;
    slug: string;
    companyName: string;
    bio: string | undefined;
    city: string;
    isVerified: boolean;
    ratingAverageBp: number;
    ratingCount: number;
    totalOrders: number;

    [key: string]: any;
}

export class MakerProductItem implements IMakerProductItem {
    productId!: string;
    title!: string;
    priceAmountMinor!: number;
    priceCurrency!: string;
    priceType!: string;
    primaryImageBlobPath!: string | undefined;

    [key: string]: any;

    constructor(data?: IMakerProductItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.productId = _data["productId"];
            this.title = _data["title"];
            this.priceAmountMinor = _data["priceAmountMinor"];
            this.priceCurrency = _data["priceCurrency"];
            this.priceType = _data["priceType"];
            this.primaryImageBlobPath = _data["primaryImageBlobPath"];
        }
    }

    static fromJS(data: any): MakerProductItem {
        data = typeof data === 'object' ? data : {};
        let result = new MakerProductItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["productId"] = this.productId;
        data["title"] = this.title;
        data["priceAmountMinor"] = this.priceAmountMinor;
        data["priceCurrency"] = this.priceCurrency;
        data["priceType"] = this.priceType;
        data["primaryImageBlobPath"] = this.primaryImageBlobPath;
        return data;
    }
}

export interface IMakerProductItem {
    productId: string;
    title: string;
    priceAmountMinor: number;
    priceCurrency: string;
    priceType: string;
    primaryImageBlobPath: string | undefined;

    [key: string]: any;
}

export class MakerProfile implements IMakerProfile {
    makerId!: string;
    slug!: string;
    companyName!: string;
    bio!: string | undefined;
    legalForm!: string | undefined;
    city!: string;
    isVerified!: boolean;
    personalPickupEnabled!: boolean;
    pickupNote!: string | undefined;
    ratingAverageBp!: number;
    ratingCount!: number;
    totalOrders!: number;
    products!: MakerProductItem[];
    reviews!: MakerReviewItem[];

    [key: string]: any;

    constructor(data?: IMakerProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.products = [];
            this.reviews = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.makerId = _data["makerId"];
            this.slug = _data["slug"];
            this.companyName = _data["companyName"];
            this.bio = _data["bio"];
            this.legalForm = _data["legalForm"];
            this.city = _data["city"];
            this.isVerified = _data["isVerified"];
            this.personalPickupEnabled = _data["personalPickupEnabled"];
            this.pickupNote = _data["pickupNote"];
            this.ratingAverageBp = _data["ratingAverageBp"];
            this.ratingCount = _data["ratingCount"];
            this.totalOrders = _data["totalOrders"];
            if (Array.isArray(_data["products"])) {
                this.products = [] as any;
                for (let item of _data["products"])
                    this.products!.push(MakerProductItem.fromJS(item));
            }
            if (Array.isArray(_data["reviews"])) {
                this.reviews = [] as any;
                for (let item of _data["reviews"])
                    this.reviews!.push(MakerReviewItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): MakerProfile {
        data = typeof data === 'object' ? data : {};
        let result = new MakerProfile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["makerId"] = this.makerId;
        data["slug"] = this.slug;
        data["companyName"] = this.companyName;
        data["bio"] = this.bio;
        data["legalForm"] = this.legalForm;
        data["city"] = this.city;
        data["isVerified"] = this.isVerified;
        data["personalPickupEnabled"] = this.personalPickupEnabled;
        data["pickupNote"] = this.pickupNote;
        data["ratingAverageBp"] = this.ratingAverageBp;
        data["ratingCount"] = this.ratingCount;
        data["totalOrders"] = this.totalOrders;
        if (Array.isArray(this.products)) {
            data["products"] = [];
            for (let item of this.products)
                data["products"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.reviews)) {
            data["reviews"] = [];
            for (let item of this.reviews)
                data["reviews"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IMakerProfile {
    makerId: string;
    slug: string;
    companyName: string;
    bio: string | undefined;
    legalForm: string | undefined;
    city: string;
    isVerified: boolean;
    personalPickupEnabled: boolean;
    pickupNote: string | undefined;
    ratingAverageBp: number;
    ratingCount: number;
    totalOrders: number;
    products: MakerProductItem[];
    reviews: MakerReviewItem[];

    [key: string]: any;
}

export class MakerReviewItem implements IMakerReviewItem {
    reviewId!: string;
    ratingStars!: number;
    comment!: string | undefined;
    createdAt!: Date;

    [key: string]: any;

    constructor(data?: IMakerReviewItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.reviewId = _data["reviewId"];
            this.ratingStars = _data["ratingStars"];
            this.comment = _data["comment"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): MakerReviewItem {
        data = typeof data === 'object' ? data : {};
        let result = new MakerReviewItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["reviewId"] = this.reviewId;
        data["ratingStars"] = this.ratingStars;
        data["comment"] = this.comment;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        return data;
    }
}

export interface IMakerReviewItem {
    reviewId: string;
    ratingStars: number;
    comment: string | undefined;
    createdAt: Date;

    [key: string]: any;
}

export class PagedDataOfMakerListItem implements IPagedDataOfMakerListItem {
    items!: MakerListItem[];
    page!: number;
    pageSize!: number;
    totalCount!: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;

    [key: string]: any;

    constructor(data?: IPagedDataOfMakerListItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.items = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(MakerListItem.fromJS(item));
            }
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
            this.totalCount = _data["totalCount"];
            this.totalPages = _data["totalPages"];
            this.hasNextPage = _data["hasNextPage"];
            this.hasPreviousPage = _data["hasPreviousPage"];
        }
    }

    static fromJS(data: any): PagedDataOfMakerListItem {
        data = typeof data === 'object' ? data : {};
        let result = new PagedDataOfMakerListItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        data["totalCount"] = this.totalCount;
        data["totalPages"] = this.totalPages;
        data["hasNextPage"] = this.hasNextPage;
        data["hasPreviousPage"] = this.hasPreviousPage;
        return data;
    }
}

export interface IPagedDataOfMakerListItem {
    items: MakerListItem[];
    page: number;
    pageSize: number;
    totalCount: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;

    [key: string]: any;
}

export class ProductDetail implements IProductDetail {
    productId!: string;
    title!: string;
    description!: string | undefined;
    priceAmountMinor!: number;
    priceCurrency!: string;
    priceType!: string;
    weightGrams!: number;
    categoryId!: string;
    makerId!: string;
    makerSlug!: string;
    makerCompanyName!: string;
    makerIsVerified!: boolean;
    images!: ProductImageItem[];

    [key: string]: any;

    constructor(data?: IProductDetail) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.images = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.productId = _data["productId"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.priceAmountMinor = _data["priceAmountMinor"];
            this.priceCurrency = _data["priceCurrency"];
            this.priceType = _data["priceType"];
            this.weightGrams = _data["weightGrams"];
            this.categoryId = _data["categoryId"];
            this.makerId = _data["makerId"];
            this.makerSlug = _data["makerSlug"];
            this.makerCompanyName = _data["makerCompanyName"];
            this.makerIsVerified = _data["makerIsVerified"];
            if (Array.isArray(_data["images"])) {
                this.images = [] as any;
                for (let item of _data["images"])
                    this.images!.push(ProductImageItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProductDetail {
        data = typeof data === 'object' ? data : {};
        let result = new ProductDetail();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["productId"] = this.productId;
        data["title"] = this.title;
        data["description"] = this.description;
        data["priceAmountMinor"] = this.priceAmountMinor;
        data["priceCurrency"] = this.priceCurrency;
        data["priceType"] = this.priceType;
        data["weightGrams"] = this.weightGrams;
        data["categoryId"] = this.categoryId;
        data["makerId"] = this.makerId;
        data["makerSlug"] = this.makerSlug;
        data["makerCompanyName"] = this.makerCompanyName;
        data["makerIsVerified"] = this.makerIsVerified;
        if (Array.isArray(this.images)) {
            data["images"] = [];
            for (let item of this.images)
                data["images"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IProductDetail {
    productId: string;
    title: string;
    description: string | undefined;
    priceAmountMinor: number;
    priceCurrency: string;
    priceType: string;
    weightGrams: number;
    categoryId: string;
    makerId: string;
    makerSlug: string;
    makerCompanyName: string;
    makerIsVerified: boolean;
    images: ProductImageItem[];

    [key: string]: any;
}

export class ProductImageItem implements IProductImageItem {
    imageId!: string;
    blobPath!: string;
    sortOrder!: number;

    [key: string]: any;

    constructor(data?: IProductImageItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.imageId = _data["imageId"];
            this.blobPath = _data["blobPath"];
            this.sortOrder = _data["sortOrder"];
        }
    }

    static fromJS(data: any): ProductImageItem {
        data = typeof data === 'object' ? data : {};
        let result = new ProductImageItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["imageId"] = this.imageId;
        data["blobPath"] = this.blobPath;
        data["sortOrder"] = this.sortOrder;
        return data;
    }
}

export interface IProductImageItem {
    imageId: string;
    blobPath: string;
    sortOrder: number;

    [key: string]: any;
}

export class RegisterMakerRequest implements IRegisterMakerRequest {
    email!: string;
    password!: string;
    fullName!: string;
    countryCodePrimary!: string;
    registrationNumber!: string;

    [key: string]: any;

    constructor(data?: IRegisterMakerRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
            this.fullName = _data["fullName"];
            this.countryCodePrimary = _data["countryCodePrimary"];
            this.registrationNumber = _data["registrationNumber"];
        }
    }

    static fromJS(data: any): RegisterMakerRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterMakerRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        data["fullName"] = this.fullName;
        data["countryCodePrimary"] = this.countryCodePrimary;
        data["registrationNumber"] = this.registrationNumber;
        return data;
    }
}

export interface IRegisterMakerRequest {
    email: string;
    password: string;
    fullName: string;
    countryCodePrimary: string;
    registrationNumber: string;

    [key: string]: any;
}

export class RegisterRequest implements IRegisterRequest {
    email!: string;
    password!: string;
    fullName!: string;
    countryCodePrimary!: string;

    [key: string]: any;

    constructor(data?: IRegisterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
            this.fullName = _data["fullName"];
            this.countryCodePrimary = _data["countryCodePrimary"];
        }
    }

    static fromJS(data: any): RegisterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        data["fullName"] = this.fullName;
        data["countryCodePrimary"] = this.countryCodePrimary;
        return data;
    }
}

export interface IRegisterRequest {
    email: string;
    password: string;
    fullName: string;
    countryCodePrimary: string;

    [key: string]: any;
}

export class RequestMagicLinkRequest implements IRequestMagicLinkRequest {
    email!: string;

    [key: string]: any;

    constructor(data?: IRequestMagicLinkRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
        }
    }

    static fromJS(data: any): RequestMagicLinkRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RequestMagicLinkRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        return data;
    }
}

export interface IRequestMagicLinkRequest {
    email: string;

    [key: string]: any;
}

export class RequestPasswordResetRequest implements IRequestPasswordResetRequest {
    email!: string;

    [key: string]: any;

    constructor(data?: IRequestPasswordResetRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
        }
    }

    static fromJS(data: any): RequestPasswordResetRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RequestPasswordResetRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        return data;
    }
}

export interface IRequestPasswordResetRequest {
    email: string;

    [key: string]: any;
}

export class UpdateMakerProfileRequest implements IUpdateMakerProfileRequest {
    bio!: string | undefined;
    bankAccount!: string | undefined;
    personalPickupEnabled!: boolean | undefined;
    pickupNote!: string | undefined;

    [key: string]: any;

    constructor(data?: IUpdateMakerProfileRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.bio = _data["bio"];
            this.bankAccount = _data["bankAccount"];
            this.personalPickupEnabled = _data["personalPickupEnabled"];
            this.pickupNote = _data["pickupNote"];
        }
    }

    static fromJS(data: any): UpdateMakerProfileRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateMakerProfileRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["bio"] = this.bio;
        data["bankAccount"] = this.bankAccount;
        data["personalPickupEnabled"] = this.personalPickupEnabled;
        data["pickupNote"] = this.pickupNote;
        return data;
    }
}

export interface IUpdateMakerProfileRequest {
    bio: string | undefined;
    bankAccount: string | undefined;
    personalPickupEnabled: boolean | undefined;
    pickupNote: string | undefined;

    [key: string]: any;
}

export class UpdateProfileRequest implements IUpdateProfileRequest {
    fullName!: string;
    phone!: string | undefined;

    [key: string]: any;

    constructor(data?: IUpdateProfileRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.fullName = _data["fullName"];
            this.phone = _data["phone"];
        }
    }

    static fromJS(data: any): UpdateProfileRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateProfileRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["fullName"] = this.fullName;
        data["phone"] = this.phone;
        return data;
    }
}

export interface IUpdateProfileRequest {
    fullName: string;
    phone: string | undefined;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}