export const DEMO_CATEGORIES = [
  { id: 'cat-1', name: '3D tisk', slug: '3d-tisk', icon: '🖨️', description: 'FDM, SLA, resin tisk na zakázku', sort_order: 1 },
  { id: 'cat-2', name: 'Klasický tisk', slug: 'klasicky-tisk', icon: '🖼️', description: 'Vizitky, letáky, brožury, plakáty', sort_order: 2 },
  { id: 'cat-3', name: 'Potisk textilu', slug: 'potisk-textilu', icon: '👕', description: 'DTF, DTG, sítotisk, sublimace', sort_order: 3 },
  { id: 'cat-4', name: 'Laser & CNC', slug: 'laser-cnc', icon: '⚡', description: 'Gravírování, řezání, frézování', sort_order: 4 },
  { id: 'cat-5', name: 'Velkoformát', slug: 'velkoformat', icon: '🖼️', description: 'Bannery, rollupy, samolepky', sort_order: 5 },
  { id: 'cat-6', name: 'Handmade', slug: 'handmade', icon: '🎨', description: 'Originální výrobky, dekorace', sort_order: 6 },
];

export const DEMO_MAKERS = [
  // --- 3D tisk ---
  {
    id: 'maker-1',
    company_name: 'PrintHub Praha',
    city: 'Praha',
    bio: 'Profesionální 3D tisk na zakázku. Specializujeme se na prototypy, funkční díly a architektonické modely. FDM i SLA tisk.',
    rating_avg: 4.8,
    rating_count: 42,
    total_orders: 156,
    is_verified: true,
    ico: '12345678',
    created_at: '2025-01-15',
    category_ids: ['cat-1'],
  },
  {
    id: 'maker-8',
    company_name: '3D Modelárna',
    city: 'Hradec Králové',
    bio: 'Resinový 3D tisk pro šperky, miniatury a detailní modely. Specializace na tabletop gaming a cosplay.',
    rating_avg: 4.4,
    rating_count: 31,
    total_orders: 124,
    is_verified: false,
    ico: '89012345',
    created_at: '2025-02-14',
    category_ids: ['cat-1'],
  },
  // --- Klasický tisk ---
  {
    id: 'maker-5',
    company_name: 'NovaPrint',
    city: 'Liberec',
    bio: 'Tiskárna s tradicí od roku 2010. Vizitky, letáky, brožury, plakáty. Ofsetový i digitální tisk nejvyšší kvality.',
    rating_avg: 4.5,
    rating_count: 19,
    total_orders: 67,
    is_verified: false,
    ico: '56789012',
    created_at: '2025-04-12',
    category_ids: ['cat-2'],
  },
  {
    id: 'maker-9',
    company_name: 'PrintXpress',
    city: 'Praha',
    bio: 'Rychlý digitální tisk do 24h. Vizitky za hodinu, letáky do druhého dne. Rozvoz po Praze zdarma.',
    rating_avg: 4.2,
    rating_count: 8,
    total_orders: 34,
    is_verified: true,
    ico: '90123456',
    created_at: '2025-05-01',
    category_ids: ['cat-2'],
  },
  // --- Potisk textilu ---
  {
    id: 'maker-3',
    company_name: 'Textil Factory',
    city: 'Ostrava',
    bio: 'Potisk triček, mikin a pracovního oblečení. DTF a sítotisk. Zakázky od 1 kusu. Expresní dodání do 48h.',
    rating_avg: 4.9,
    rating_count: 67,
    total_orders: 312,
    is_verified: true,
    ico: '34567890',
    created_at: '2024-11-10',
    category_ids: ['cat-3'],
  },
  {
    id: 'maker-10',
    company_name: 'TrikoMania',
    city: 'Brno',
    bio: 'Sublimační a DTG potisk. Sportovní dresy, firemní kolekce, merch pro kapely. Návrh grafiky v ceně.',
    rating_avg: 4.6,
    rating_count: 22,
    total_orders: 98,
    is_verified: true,
    ico: '10234567',
    created_at: '2025-01-20',
    category_ids: ['cat-3'],
  },
  // --- Laser & CNC ---
  {
    id: 'maker-4',
    company_name: 'LaserCut Studio',
    city: 'Plzeň',
    bio: 'Laserové gravírování a řezání. Dřevo, plexisklo, kůže, papír. Personalizované dárky a firemní předměty.',
    rating_avg: 4.7,
    rating_count: 35,
    total_orders: 178,
    is_verified: true,
    ico: '45678901',
    created_at: '2025-03-05',
    category_ids: ['cat-4'],
  },
  {
    id: 'maker-11',
    company_name: 'CNC Dílna Vysočina',
    city: 'Jihlava',
    bio: 'CNC frézování dřeva, plastu a hliníku. Výroba nábytku na míru, prototypy, dekorativní prvky.',
    rating_avg: 4.3,
    rating_count: 11,
    total_orders: 42,
    is_verified: true,
    ico: '11234567',
    created_at: '2025-03-28',
    category_ids: ['cat-4'],
  },
  // --- Velkoformát ---
  {
    id: 'maker-6',
    company_name: 'VelkoTisk CZ',
    city: 'Olomouc',
    bio: 'Velkoformátový tisk — bannery, rollupy, samolepky, polepy aut. Tisk na plátno a fotopapír. Montáž po celé ČR.',
    rating_avg: 4.3,
    rating_count: 14,
    total_orders: 45,
    is_verified: true,
    ico: '67890123',
    created_at: '2025-04-28',
    category_ids: ['cat-5'],
  },
  {
    id: 'maker-12',
    company_name: 'SignPro Pardubice',
    city: 'Pardubice',
    bio: 'Reklamní cedule, světelné boxy, polepy výloh a aut. Kompletní výroba a montáž. Působíme v celém Pardubickém kraji.',
    rating_avg: 4.1,
    rating_count: 9,
    total_orders: 28,
    is_verified: false,
    ico: '12234567',
    created_at: '2025-04-10',
    category_ids: ['cat-5'],
  },
  // --- Handmade ---
  {
    id: 'maker-7',
    company_name: 'Handmade by Terka',
    city: 'České Budějovice',
    bio: 'Originální ručně vyráběné dekorace, šperky a doplňky z pryskyřice, dřeva a kovu. Každý kus je unikát.',
    rating_avg: 5.0,
    rating_count: 23,
    total_orders: 89,
    is_verified: true,
    ico: '78901234',
    created_at: '2025-01-30',
    category_ids: ['cat-6'],
  },
  {
    id: 'maker-13',
    company_name: 'Keramika Nová',
    city: 'Zlín',
    bio: 'Ručně točená keramika — hrnky, misky, vázy. Každý kus glazován originálním vzorem. Přírodní materiály.',
    rating_avg: 4.8,
    rating_count: 17,
    total_orders: 53,
    is_verified: true,
    ico: '13234567',
    created_at: '2025-02-05',
    category_ids: ['cat-6'],
  },
  // --- Multi-category ---
  {
    id: 'maker-2',
    company_name: 'MakerSpace Brno',
    city: 'Brno',
    bio: 'Komunitní dílna s 3D tiskárnami, laserem a CNC frézkou. Vyrábíme prototypy, reklamní předměty a originální dárky.',
    rating_avg: 4.6,
    rating_count: 28,
    total_orders: 89,
    is_verified: true,
    ico: '23456789',
    created_at: '2025-02-20',
    category_ids: ['cat-1', 'cat-4'],
  },
];

export const DEMO_PRODUCTS = [
  // --- 3D tisk (maker-1, maker-8, maker-2) ---
  {
    id: 'prod-1',
    maker_id: 'maker-1',
    title: 'FDM 3D tisk na zakázku',
    description: 'Tisk z PLA, PETG, ASA. Cena za hodinu tisku. Minimální objednávka 1 kus.',
    price: 350,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-01',
  },
  {
    id: 'prod-2',
    maker_id: 'maker-1',
    title: 'SLA Resin tisk — detailní modely',
    description: 'Přesnost 0.05mm. Ideální pro šperky, miniatury a prototypy.',
    price: 500,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-15',
  },
  {
    id: 'prod-15',
    maker_id: 'maker-8',
    title: 'Miniatury pro stolní hry',
    description: 'Detailní resinové figurky 28–32mm. D&D, Warhammer, vlastní návrhy. Barvy na přání.',
    price: 120,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-02-20',
  },
  {
    id: 'prod-8',
    maker_id: 'maker-2',
    title: 'Prototyp z 3D tisku + CNC',
    description: 'Kompletní prototyp — 3D tištěné díly + CNC frézované kovové komponenty.',
    price: 0,
    price_type: 'on_request' as const,
    images: [],
    is_active: true,
    category_id: 'cat-1',
    created_at: '2025-03-10',
  },

  // --- Klasický tisk (maker-5, maker-9) ---
  {
    id: 'prod-5',
    maker_id: 'maker-5',
    title: '1000 ks vizitek',
    description: '350g křídový papír, oboustranný plnobarevný tisk, laminace. Dodání do 3 dnů.',
    price: 890,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-2',
    created_at: '2025-04-01',
  },
  {
    id: 'prod-9',
    maker_id: 'maker-5',
    title: 'Brožury A5 — sešitová vazba',
    description: '135g lesklý křídový papír, plnobarevný tisk. Od 50 ks. Včetně grafické úpravy.',
    price: 2400,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-2',
    created_at: '2025-04-10',
  },
  {
    id: 'prod-10',
    maker_id: 'maker-9',
    title: 'Letáky A4 — digitální tisk',
    description: 'Express tisk do 24h. 150g křída, jednostranný nebo oboustranný. Rozvoz po Praze.',
    price: 3,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-2',
    created_at: '2025-05-05',
  },

  // --- Potisk textilu (maker-3, maker-10) ---
  {
    id: 'prod-3',
    maker_id: 'maker-3',
    title: 'Potisk triček — DTF',
    description: 'Plnobarevný potisk. Od 1 kusu. Trička značky Fruit of the Loom.',
    price: 299,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-3',
    created_at: '2025-02-10',
  },
  {
    id: 'prod-11',
    maker_id: 'maker-3',
    title: 'Potisk mikiny s kapucí',
    description: 'Kvalitní mikina 280g/m² s DTF potiskem. Přední i zadní strana. Od 1 kusu.',
    price: 549,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-3',
    created_at: '2025-02-15',
  },
  {
    id: 'prod-12',
    maker_id: 'maker-10',
    title: 'Sportovní dresy — sublimace',
    description: 'Plně sublimovaný dres. Vlastní design, jména, čísla. Ideální pro týmy. Min. 10 ks.',
    price: 450,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-3',
    created_at: '2025-01-25',
  },

  // --- Laser & CNC (maker-4, maker-11, maker-2) ---
  {
    id: 'prod-4',
    maker_id: 'maker-4',
    title: 'Gravírování do dřeva',
    description: 'Laserové gravírování fotografií, textů a log do bukového nebo dubového dřeva.',
    price: 450,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-4',
    created_at: '2025-03-20',
  },
  {
    id: 'prod-13',
    maker_id: 'maker-4',
    title: 'Řezání plexiskla na míru',
    description: 'Čiré, mléčné nebo barevné plexisklo. Přesné laserové řezání do 10mm tloušťky.',
    price: 200,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-4',
    created_at: '2025-03-25',
  },
  {
    id: 'prod-14',
    maker_id: 'maker-11',
    title: 'CNC nábytek na míru',
    description: 'Poličky, stolky, dekorace z překližky a masivu. Návrh v ceně. Dodání do 14 dnů.',
    price: 0,
    price_type: 'on_request' as const,
    images: [],
    is_active: true,
    category_id: 'cat-4',
    created_at: '2025-04-05',
  },
  {
    id: 'prod-16',
    maker_id: 'maker-2',
    title: 'Laserové gravírování kovů',
    description: 'Gravírování do nerezové oceli, hliníku a mosazi. Štítky, klíčenky, nástroje.',
    price: 150,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-4',
    created_at: '2025-03-12',
  },

  // --- Velkoformát (maker-6, maker-12) ---
  {
    id: 'prod-6',
    maker_id: 'maker-6',
    title: 'Roll-up banner 85×200 cm',
    description: 'Kvalitní roll-up s hliníkovou konstrukcí a plnobarevným tiskem.',
    price: 1490,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-5',
    created_at: '2025-04-15',
  },
  {
    id: 'prod-17',
    maker_id: 'maker-6',
    title: 'Polep dodávky — celopolep',
    description: 'Kompletní polep dodávky reklamní grafikou. Návrh, tisk i aplikace. Záruka 5 let.',
    price: 18900,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-5',
    created_at: '2025-04-20',
  },
  {
    id: 'prod-18',
    maker_id: 'maker-12',
    title: 'Světelný box — LED',
    description: 'Venkovní reklamní světelný box s LED podsvícením. Hliníkový rám, výměnná grafika.',
    price: 4500,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-5',
    created_at: '2025-04-12',
  },

  // --- Handmade (maker-7, maker-13) ---
  {
    id: 'prod-7',
    maker_id: 'maker-7',
    title: 'Pryskyřicový přívěsek na míru',
    description: 'Ručně vyráběný přívěsek z epoxidové pryskyřice. Barvy a design dle vašeho přání.',
    price: 350,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-6',
    created_at: '2025-02-28',
  },
  {
    id: 'prod-19',
    maker_id: 'maker-7',
    title: 'Dřevěná dekorace s pryskyřicí',
    description: 'Unikátní river table podtácky a dekorace z ořechového dřeva a barevné pryskyřice.',
    price: 690,
    price_type: 'from' as const,
    images: [],
    is_active: true,
    category_id: 'cat-6',
    created_at: '2025-03-05',
  },
  {
    id: 'prod-20',
    maker_id: 'maker-13',
    title: 'Keramický hrnek — ručně točený',
    description: 'Originální hrnek z bílé kameniny. Glazura v přírodních tónech. Objem 300 ml.',
    price: 420,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-6',
    created_at: '2025-02-10',
  },
  {
    id: 'prod-21',
    maker_id: 'maker-13',
    title: 'Sada misek — 4 ks',
    description: 'Sada čtyř ručně točených misek na cereálie. Každý kus je jedinečný. Bezpečné do myčky.',
    price: 1290,
    price_type: 'fixed' as const,
    images: [],
    is_active: true,
    category_id: 'cat-6',
    created_at: '2025-02-15',
  },
];
