<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Makables.Core.Domain\Makables.Core.Domain.csproj" />
    <ProjectReference Include="..\Makables.Core.AppServices\Makables.Core.AppServices.csproj" />
    <ProjectReference Include="..\Makables.Infra.Database\Makables.Infra.Database.csproj" />
  </ItemGroup>

</Project>
